NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 100 	
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 100	
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 100 	

NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 100				
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 100					
NDefines.NMilitary.NAVAL_EQUIPMENT_BASE_COST = 100
NDefines.NMilitary.NAVAL_EQUIPMENT_RAMP_COST = 100
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 100
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 100

NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 1.0				
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 1.0				
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1.0				
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1.0